apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 10 # 10sec
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 100 # 200sec
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster && sleep 600
          restartPolicy: Never